import { SaleItem } from "@/types";

export const mockSales: SaleItem[] = [
  {
    id: "1",
    name: "Chicken Breast",
    store: "Neighborhood Market",
    unit: "lb",
    salePrice: 2.49,
    regularPrice: 3.99,
  },
  {
    id: "2",
    name: "Black Beans",
    store: "Neighborhood Market",
    unit: "can",
    salePrice: 0.99,
    regularPrice: 1.59,
  },
  {
    id: "3",
    name: "Brown Rice",
    store: "Neighborhood Market",
    unit: "lb",
    salePrice: 1.49,
    regularPrice: 2.19,
  },
  {
    id: "4",
    name: "Eggs",
    store: "Neighborhood Market",
    unit: "dozen",
    salePrice: 2.29,
    regularPrice: 3.19,
  },
  {
    id: "5",
    name: "Spinach",
    store: "Neighborhood Market",
    unit: "bag",
    salePrice: 1.99,
    regularPrice: 2.99,
  },
  {
    id: "6",
    name: "Pasta",
    store: "Neighborhood Market",
    unit: "box",
    salePrice: 1.19,
    regularPrice: 1.79,
  },
  {
    id: "7",
    name: "Tomato Sauce",
    store: "Neighborhood Market",
    unit: "jar",
    salePrice: 1.79,
    regularPrice: 2.49,
  },
  {
    id: "8",
    name: "Onion",
    store: "Neighborhood Market",
    unit: "lb",
    salePrice: 0.99,
    regularPrice: 1.49,
  },
  {
    id: "9",
    name: "Garlic",
    store: "Neighborhood Market",
    unit: "bulb",
    salePrice: 0.59,
    regularPrice: 0.89,
  },
  {
    id: "10",
    name: "Ground Turkey",
    store: "Neighborhood Market",
    unit: "lb",
    salePrice: 2.99,
    regularPrice: 4.49,
  },
];
